### ISSUE TITLE
postinstall does not work on windows

### ISSUE THREAD

**Issue by craigklem** [hyperjump-io/json-pointer#5]
installing library in windows fails due to rm command in postinstall. Consider using cross platform library like rimraf to achieve the same result.

**Comment by jdesrosiers** [comment]
I might not be able to get to this this weekend. If you need a workaround, you can pin to version `v0.9.1` before this was introduced.

**Comment by jdesrosiers** [comment]
Fix published as v0.9.3. Sorry, such a small change took me so long. I'll have much more time for open source projects very soon. Thanks to @yamadayutaka for confirming that it works on windows.
